/****************************************************************************************************
  ESP32-S3 + ILI9341(FSPI) + I2S + SD(FPI) + Encoder1. Maleksm MOD + battery + Mute. Divider (38.5�99.2) - 1st or 2nd pin.
****************************************************************************************************/
/* Generated by �Radio - simple myoptions.h generator - v0.9.0
https://trip5.github.io/ehRadio_myoptions/generator.html?b=ESP32-S3-DevKitC-1_44Pin&r=72,1,2,4,6,7,8,19,42,43,54,75,67,68&i=1,2,3,4,15,16,17,28,29,30,39,45,46,47,41,42&v=9,10,-1,14,17,16,18,6,5,4,39,41,42,40,21,47
Put this file next to yoRadio.ino and restart Arduino IDE. */

#ifndef myoptions_h
#define myoptions_h

#define L10N_LANGUAGE HU // HU NL PL RU EN EL Enter your own language here!!
#define NAMEDAYS_FILE HU // HU, PL, NL
#define CLOCK_TTS_LANGUAGE "hu" //Default language TTS e.g. pl,en,de,ru,fr,hu
//#define AM_PM_STYLE
//#define USDATE   //US Date format
#define DIRECT_CHANNEL_CHANGE 
//#define MetaStationNameSkip 
//#define IMPERIALUNIT

//#define LED_BUILTIN_S3    48      /* S3-onboard RGB led pin */
#define USE_BUILTIN_LED   false     /* Use S3-onboard RGB led */
#define DSP_INVERT_TITLE  false     /*  Invert station name colors (display title). Default is "true"  */
#define EXT_WEATHER       true     /*  Extended weather. Default is "true"  */
#define RSSI_DIGIT        false     /* Graphic/digital Wi-Fi icon. (false - ladder, true - numbers) */
//#define BITRATE_FULL      true      /* Bitrate graphic icon. Default is "true" */ 

/* Display */
#define DSP_MODEL   DSP_ST7789_76  /* Select ST7789*/
/* **************************************** */

/* TFT */
#define TFT_CS          10    /* (FSPI CS0)        can be CS pin ( ) */
#define TFT_RST          8    /* SPI RST pin. (-1 if connect to EN, RST) */
#define TFT_DC           9    /* (FSPI HD)         can be DC, RS */
#define TFT_MOSI        11  // 23
#define TFT_SCK         12  // 18
#define BRIGHTNESS_PIN   7    /* Pin for brightness (output 0 - 3v3)    (FSPI WP)    can be BLK, BL */
					/* Connect TFT_MOSI  to pin  11     (FSPI D)      can be SDA, DIN, SDI */
					/* Connect TFT_SCLK  to pin  12     (FSPI CLK)   can be SCL, SCK, CLK */
/* **************************************** */

/*  I2S DAC    */
#define I2S_DOUT    	5    /*  = (CS4344=SDIN)  DIN connection. Should be set to 255 if the board is not used */
#define I2S_BCLK      4    /*  = (CS4344=SCLK)  BCLK Bit clock */
#define I2S_LRC       6    /*  = (CS4344=LRCLK) WSEL Left Right Clock */
#define I2S_MCLK     13    /*  MCLK - Master Clock . MOD Maleksm (from version v0.9.535(m)-3.4.2p) */
/* **************************************** */

/*  ENCODERs  */
//#define ENC_BTNL              	2       /*  1st encoder left rotation (S1, DT)*/
//#define ENC_BTNR              	1       /*  1st encoder right rotation (S2, CLK) */
//#define ENC_BTNB              	3       /*  1st encoder button (Key, SW)*/
//#define ENC2_BTNL             6       /*  2nd encoder left rotation (S1, DT)*/
//#define ENC2_BTNR             5       /*  2nd encoder right rotation (S2, CLK) */
//#define ENC2_BTNB             4       /*  2nd encoder button (Key, SW)*/
//#define ENC_INTERNALPULLUP    false     /*  Enable the weak pull up resistors. Default is "true"  */
//#define ENC2_INTERNALPULLUP   false   /*  Enable the weak pull up resistors. Default is "true"  */

/*  BUTTONS  */
#define BTN_LEFT    					3    /*  VolDown, Prev */
#define BTN_CENTER    			  1    /*  Play, Stop, Show playlist */
#define BTN_RIGHT   				  2    /*  VolUp, Next */
#define ENC_INTERNALPULLUP    false
/* **************************************** */

/*  Other settings.  */
//#define MUTE_PIN    47           /*  MUTE Pin */
//#define MUTE_VAL    LOW     /*  Write this to MUTE_PIN when player is stopped. Default is "HIGH" */
#define PLAYER_FORCE_MONO false   /*  mono option on boot - false stereo, true mono. Default is "false" */
//#define WAKE_PIN              255
//#define NAME_STRIM                /* Show station name from stream. (MOD Maleksm)  */

//#define DOWN_LEVEL           	200      /* lowest level brightness (from 0 to 255, default "2"). (MOD Maleksm) */
//#define DOWN_INTERVAL     	  300     /* interval for BacklightDown in sec (60 sec = 1 min, default "60"). (MOD Maleksm) */
/* ***************************************** */

#endif
